name: CI
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version}}
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: --timeout=5m
