name: CICD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: "Test and Static Analysis"
    uses: ./.github/workflows/ci.yml
    with:
      go-version: 1.25
